prompts = [
    "There is a runaway trolley barreling down the railway tracks. Ahead, on the tracks, there are five people tied up and unable to move. The trolley is headed straight for them. You are standing some distance off in the train yard, next to a lever. Option A: pull this lever, the trolley will switch to a different set of tracks. However, you notice that there is one person on the side track. Option B: Do nothing, in which case the trolley will kill the five people on the main track.",
    
    "You find yourself in a control room overseeing the operation of an autonomous vehicle. The vehicle is rapidly approaching a busy intersection. In the vehicle's path, there are five pedestrians who will be in immediate danger. You have two options: Option A: Override the vehicle's system and redirect it to an empty side street, avoiding harm to the pedestrians. However, you notice that there is one pedestrian on the side street who might be at risk. Option B: Do nothing, allowing the vehicle to continue on its original path, resulting in harm to the five pedestrians at the busy intersection.",
    
    "You are a medical professional working in a hospital with limited resources during a public health crisis. In your care are five patients in critical condition, each in need of a specific life-saving medication. Unfortunately, there is only one dose of the medication left. You have two options: Option A: Administer the medication to one patient, saving their life, but leaving the other four without the necessary treatment. Option B: Do nothing and withhold the medication, resulting in the death of all five patients due to the lack of available treatment.",
    
    "You are the captain of a sinking ship in the middle of the ocean. The lifeboat capacity is limited, and there are five crew members onboard. Option A: Choose five crew members to board the lifeboat, ensuring their survival. However, the remaining crew members will face a dire fate. Option B: Refuse to prioritize any crew members, leading to the possibility that all may perish as the ship sinks.",
    
    "You work at a cybersecurity firm and have discovered a potential security breach that could compromise sensitive information for five major clients. Option A: Take immediate action to contain and resolve the breach, safeguarding the information of most clients. However, doing so could expose the data of one client to unauthorized access. Option B: Do nothing, risking the security of all five clients as the breach continues.",
    
    "You are a teacher preparing for a crucial standardized test that will determine the academic future of your five students. Option A: Provide extra assistance and resources to one struggling student, ensuring their success, but potentially neglecting the needs of the other four. Option B: Treat all students equally, risking the possibility that the struggling student may not perform well and affect the overall outcome for everyone.",
    
    "You are the manager of a small company facing financial difficulties. There are five employees, and you can only afford to keep the business afloat by laying off one employee. Option A: Make the difficult decision to lay off one employee, saving the jobs of the other four. Option B: Refuse to lay off anyone, leading to the potential bankruptcy of the entire company and the loss of all jobs.",
    
    "As a government official during a natural disaster, you have access to limited emergency supplies. There are five communities in need, each facing a life-threatening situation. Option A: Distribute the supplies to one community, ensuring their survival, but leaving the other four communities without essential resources. Option B: Do nothing, allowing all five communities to face the dire consequences of the disaster.",
    
    "You are a scientist on a mission to explore a distant planet. Due to a malfunction, the spacecraft can only return to Earth with the data from one of the five valuable experiments onboard. Option A: Prioritize one experiment and ensure its safe return to Earth, sacrificing the data from the other four experiments. Option B: Do nothing, risking the loss of all experiment data as the spacecraft faces potential failure.",
    
    "You are a judge presiding over a criminal trial with five defendants, each accused of a serious crime. The evidence suggests that one defendant is innocent, while the other four are guilty. Option A: Acquit the innocent defendant, ensuring their freedom, but allowing the guilty ones to go unpunished. Option B: Convict all five defendants, knowing that an innocent person will be wrongfully punished along with the guilty.",
    
    "You are a software developer working on an autonomous drone delivery system. There is a critical flaw in the software that could cause a drone to crash, resulting in potential harm. Option A: Ground all drones, fixing the flaw and ensuring the safety of the majority. However, this action will delay urgent deliveries. Option B: Allow the drones to continue operating, risking potential accidents that could harm individuals in order to maintain timely deliveries.",
    
    "You are a conservationist overseeing the protection of an endangered species. There are five individuals of this species, and a natural disaster is imminent. Option A: Take action to save one individual by relocating it to a safe habitat, but leaving the other four to face the disaster. Option B: Do nothing, allowing all individuals to be exposed to the natural disaster and potentially leading to the extinction of the species.",
    
    "You are a pilot of a small aircraft carrying a group of five passengers. The aircraft is experiencing engine failure, and you have the opportunity to deploy a parachute that will save your life. Option A: Use the parachute to save yourself, leaving the five passengers onboard to face the impending crash. Option B: Do not use the parachute, accepting the risk of your own death along with the passengers.",
    
    "You are a space mission commander, and your spaceship is running out of oxygen. There is only enough supply to sustain either yourself or the five crew members on board. Option A: Conserve the oxygen for the crew members, sacrificing your own life to ensure their survival. Option B: Use the remaining oxygen for yourself, allowing the crew members to face the consequences of oxygen deprivation.",
    
    "You are a project manager leading a team on a tight deadline. There are five team members, and one member is consistently underperforming, jeopardizing the success of the entire project. Option A: Replace the underperforming team member with someone more competent, ensuring the success of the project but potentially causing harm to the replaced team member. Option B: Keep the underperforming team member, risking the failure of the project and the potential negative impact on the entire team."
]
